<!-- Javascripts -->
<script src="<?php echo base_url()?>assets/plugins/jquery/jquery-2.2.0.min.js"></script>
<!-- <script src="<?php echo base_url()?>assets/js/jquery-3.2.1.min.js"></script> -->
<script src="<?php echo base_url()?>assets/plugins/materialize/js/materialize.min.js"></script>
<script src="<?php echo base_url()?>assets/plugins/material-preloader/js/materialPreloader.min.js"></script>
<script src="<?php echo base_url()?>assets/plugins/jquery-blockui/jquery.blockui.js"></script>
<script src="<?php echo base_url()?>assets/plugins/waypoints/jquery.waypoints.min.js"></script>
<script src="<?php echo base_url()?>assets/plugins/counter-up-master/jquery.counterup.min.js"></script>
<script src="<?php echo base_url()?>assets/plugins/jquery-sparkline/jquery.sparkline.min.js"></script>
<script src="<?php echo base_url()?>assets/plugins/chart.js/chart.min.js"></script>
<script src="<?php echo base_url()?>assets/plugins/flot/jquery.flot.min.js"></script>
<script src="<?php echo base_url()?>assets/plugins/flot/jquery.flot.time.min.js"></script>
<script src="<?php echo base_url()?>assets/plugins/flot/jquery.flot.symbol.min.js"></script>
<script src="<?php echo base_url()?>assets/plugins/flot/jquery.flot.resize.min.js"></script>
<script src="<?php echo base_url()?>assets/plugins/flot/jquery.flot.tooltip.min.js"></script>
<script src="<?php echo base_url()?>assets/plugins/curvedlines/curvedLines.js"></script>
<script src="<?php echo base_url()?>assets/plugins/peity/jquery.peity.min.js"></script>
<script src="<?php echo base_url()?>assets/js/alpha.min.js"></script>
<script src="<?php echo base_url()?>assets/js/pages/form_elements.js"></script>
<script src="<?php echo base_url()?>assets/plugins/dropzone/dropzone.min.js"></script>
<script src="<?php echo base_url()?>assets/plugins/dropzone/dropzone-amd-module.min.js"></script>
<script src="<?php echo base_url()?>assets/plugins/datatables/js/jquery.dataTables.min.js"></script>
<script src="<?php echo base_url()?>assets/js/pages/table-data.js"></script>
<script src="<?php echo base_url()?>assets/plugins/jquery-blockui/jquery.blockui.js"></script>
<script src="<?php echo base_url()?>assets/plugins/google-code-prettify/prettify.js"></script>
<script src="<?php echo base_url()?>assets/js/pages/ui-modals.js"></script>
<script src="<?php echo base_url()?>assets/plugins/google-code-prettify/prettify.js"></script>
<!-- <script src="<?php echo base_url()?>assets/plugins/sweetalert/sweetalert.min.js"></script> -->
<!-- <script src="<?php echo base_url()?>assets/js/pages/miscellaneous-sweetalert.js"></script> -->
<!-- <script src="<?php echo base_url()?>assets/js/pages/dashboard.js"></script> -->
